sudo: required
services:
    - docker
    
before_install:
    - docker build -t kallis07/docker-react -f Dockerfile.dev .
    
script:
    - docker run kallis07/docker-react npm run test -- --coverage
